language: node_js

node_js:
  - 7.5.0

install:
  - npm i --silent --no-optional -g @angular/cli@1.0.0-beta.32.3
  - npm i --silent --no-optional -g angular-cli-ghpages

script:
  - npm i --silent --no-optional;
  - ng build --prod --aot --base-href "https://vandut.github.io/archetype/"
  - angular-cli-ghpages --no-silent --repo=https://GH_TOKEN@github.com/vandut/archetype.git --name="Konrad Bielak" --email=konrad.bielak@gmail.com

branches:
  only:
    - master
