language: node_js

node_js:
  - 7.5.0

cache:
  directories:
  - node_modules

env:
  global:
    # node-gyp: Node.js v4 (or io.js v3) compiler requirements
    # https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
    - CXX=g++-4.8

install:
  - npm i --silent --no-optional -g @angular/cli@1.0.0-beta.31
  - npm i --silent --no-optional -g angular-cli-ghpages

script:
  - npm i --silent --no-optional
  - ng build --prod --aot --progress=false --base-href "https://vandut.github.io/archetype/"
  - cp dist/index.html dist/404.html
  - angular-cli-ghpages --repo="https://GH_TOKEN@github.com/vandut/archetype.git" --name="Konrad Bielak build bot" --email="konrad.bielak+build.bot@gmail.com"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

# a build will finish as soon as a job has failed
matrix:
  fast_finish: true

#only building specific branches
branches:
  only:
    - master

notifications:
  email:
    on_failure: change
    on_success: change
